name: Node.js Package
on:
    workflow_dispatch:
    release:
        types: [published]
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true
jobs:
    publish-npm:
        runs-on: ubuntu-20.04
        env:
            TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
            TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org/
            - name: Cache yarn
              uses: actions/cache@v3
              with:
                  path: .yarn/cache
                  key: yarn-cache-node-20
            - run: yarn install --immutable
            - name: Build and publish
              uses: ./.github/actions/npm
              env:
                  NPM_TOKEN: ${{secrets.npm_token}}
